### PR TITLE
fix: retry-after should be in seconds when specified timeWindow

### LINKED ISSUE #301: Incorrect Retry-After header value
### Prerequisites

- [X] I have written a descriptive issue title
- [X] I have searched existing issues to ensure the bug has not already been reported

### Fastify version

4.17.0

### Plugin version

8.0.0

### Node.js version

20.2.0

### Operating system

Linux

### Operating system version (i.e. 20.04, 11.3, 10)

22.04.2

### Description

It seems the value of the Retry-After header is expressed in milliseconds instead of seconds (or an http-date) as specified by [RFC 9110](https://www.rfc-editor.org/rfc/rfc9110.html#name-retry-after).

### Steps to Reproduce

`@fastify/rate-limit` options:
```typescript
const options = {
  max: 5,
  timeWindow: '1 minute',
};
```

Headers on 429 response:
```http
x-ratelimit-limit: 5
x-ratelimit-remaining: 0
x-ratelimit-reset: 58
retry-after: 60000
```

### Expected Behavior

The value of `Retry-After` should be `60` (i.e., 1 minute in seconds), not `60000`.

### PR DESCRIPTION
**Pull request by Uzlopak**
Fixes #301

#### Checklist

- [ ] run `npm run test` and `npm run benchmark`
- [ ] tests and/or benchmarks are included
- [ ] documentation is changed or added
- [ ] commit message and code follows the [Developer's Certification of Origin](https://github.com/fastify/.github/blob/master/CONTRIBUTING.md#developers-certificate-of-origin-11)
      and the [Code of conduct](https://github.com/fastify/.github/blob/master/CODE_OF_CONDUCT.md)

### CODE REVIEW

File: index.js [hunk 1]
```diff
@@ -246,7 +246,7 @@ function rateLimitRequestHandler (params, pluginComponent) {
     if (params.addHeaders[params.labels.rateRemaining]) { res.header(params.labels.rateRemaining, 0) }
     if (params.addHeaders[params.labels.rateReset]) { res.header(params.labels.rateReset, timeLeft) }
     if (params.addHeaders[params.labels.retryAfter]) {
-      const resetAfterTime = (params.enableDraftSpec) ? timeLeft : params.timeWindow
+      const resetAfterTime = (params.enableDraftSpec ? timeLeft : params.timeWindow / 1000 | 0)
```
Comment (Uzlopak) [inline index.js:249]: Maybe we should precalculate it and have a params.timeWindowsInS.

But my first try to precalculate it was not successful. So want to know if we should precalculate it.

Comment (Uzlopak) [reply index.js]: solved

**Review by climba03003 — APPROVED** [review]
